# Generated by Django 6.0.1 on 2026-01-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            options={
                'db_table': 'readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
